name: 'Enforce Terraform Format (`terraform fmt`)'
description: 'A GitHub Action that enforces Terraform formatting by running terraform fmt on committed files. The workflow fails if any files need reformatting.'
branding:
  icon: code
  color: gray-dark
inputs:
  terraform_version:
    description: 'The Terraform version to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.terraform_version }}
