name: 'Enforce Terraform Format (fmt)'
description: 'Status check which fails if any of the committed files have changes after running `terraform fmt`'
branding:
  icon: code
  color: gray-dark
inputs:
  terraform_version:
    description: 'The Terraform version to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.terraform_version }}
