name: 'Enforce Terraform Format (`terraform fmt`)'
description: 'A GitHub Action that enforces Terraform formatting standards by running `terraform fmt` on all committed files. The workflow will fail if any files require reformatting.'
branding:
  icon: code
  color: gray-dark
inputs:
  terraform_version:
    description: 'The Terraform version to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.terraform_version }}
