name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      # Check out full depth to compare file changes between commits
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git to allow to commit files in steps
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      # Expect a failure when terraform_version is not passed
      - name: "Test: Terraform version input omitted"
        id: fail_no_version
        continue-on-error: true
        uses: ./
      - name: "Assert Failed: Terraform version input omitted"
        if: steps.fail_no_version.outcome != 'failure'
        run: exit 1

      # Raise failure when Terraform version is not valid
      - name: "Test: Invalid Terraform version"
        id: fail_invalid_version
        continue-on-error: true
        uses: ./
        with:
          terraform_version: asdf
      - name: "Assert Failed: Invalid Terraform version"
        if: steps.fail_invalid_version.outcome != 'failure'
        run: exit 1

      # Raise failure when a non-existent Terraform version is passed
      - name: "Test: Missing (non-existent) Terraform version"
        id: fail_missing_version
        continue-on-error: true
        uses: ./
        with:
          terraform_version: 999.999.999
      - name: "Assert Failed: Missing (non-existent) Terraform version"
        if: steps.fail_missing_version.outcome != 'failure'
        run: exit 1

      - name: "Modify test.tf file to introduce a formatting issue"
        run: |
          sed -i '2s/[[:space:]]//g' test.tf
          echo 'resource "random_pet" "test" {length=5}' > pets.tf
      - name: Commit the munged `test.tf`
        run: |
          git add . 
          git commit -m "Running tests"
      - name: "Test: Non-formatted Terraform file"
        id: failure_step
        continue-on-error: true
        uses: ./
        with:
          terraform_version: 1.9.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Assert Failed: Non-formatted Terraform file"
        if: steps.failure_step.outcome != 'failure'
        run: exit 1

        # Commit formatted file to simulate a successful run
      - name: Commit formatted files
        run: |
          git add . 
          git commit -m "Running tests"
      - name: "Test: All files formatted correctly - post comment"
        uses: ./
        with:
          terraform_version: 1.9.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Print message to console when GitHub Token is not passed
      - name: "Modify test.tf file to introduce a formatting issue"
        run: |
          sed -i '2s/[[:space:]]//g' test.tf
          echo 'resource "random_pet" "test" {length=5}' > pets.tf
      - name: "Test: All files formatted correctly - print to console"
        id: failure_step_wo_token
        uses: ./
        with:
          terraform_version: 1.9.8
        continue-on-error: true
      - name: "Assert Failed: All files formatted correctly - print to console"
        if: steps.failure_step_wo_token.outcome != 'failure'
        run: exit 1

  check_version:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if tag already exists
        run: |
          git fetch --tags
          TAG=$(cat VERSION)
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
            exit 1
          fi
